server:
  port: 8082

spring:
  application:
    name: currency-data-provider
  output.ansi.enabled: ALWAYS

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
